//
// Created by Oğuz Kerem Yıldız on 8.01.2023.
//

#ifndef SEQUENCEPROCESSING_CPP_LABELLEDSENTENCE_H
#define SEQUENCEPROCESSING_CPP_LABELLEDSENTENCE_H

#endif //SEQUENCEPROCESSING_CPP_LABELLEDSENTENCE_H
